spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recruitment_2
    username: postgres
    password: a
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Bangkok

server:
  port: 18080
  forward-headers-strategy: framework

app:
  jwtSecret: abcdefghijklmnopqrstuvwxyz1234567890aabbccddeeffgghhiillkk
  jwtExpiration: 86400000