spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recrutement
    username: root
    password: a
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false